namespace TimeParabox;

public static class Puzzles {

    public static IReadOnlyList<Hub> hubs { get; } = new List<Hub> {
        new("Intro",
            new InterPuzzleMovement("aa") { trailingDelay = 5000 },
            new InterPuzzleMovement(">vvv"),
            new Puzzle(1, "^^>>>vv^^^<<<<"),
            new Puzzle(2, "<<^^^^>>vvv>v<<^<v>v>><"),
            new Puzzle(3, "^^^>>vvv<v>>v>>^<<<<^<<vv>^^^<^>"),
            new InterPuzzleMovement("<<vvv"),
            new Puzzle(4, ">^^^<^>>>>>>v>^^^^vvvvvv<<<<"),
            new Puzzle(5, "vv<<<<^<<v>>^>vv>>>^^"),
            new Puzzle(6, "^^<<vvv<<>>^>vvvv<<>>>>>^^>>vv<<^^^^>^<<^^v>v<vv>>"),
            new Puzzle(7, ">>>^^<<<v<<^^>>vvv<<"),
            new Puzzle(8, "vv>>v>^^^^v<^>>^>>vv<vvvv<<<"),
            new Puzzle(9, "^<<vv<v>>>>v>>^<<<>>>"),
            new InterPuzzleMovement(">vvv<<<v") { leadingDelay = 8800 }),
        new("Enter",
            new InterPuzzleMovement("v<<<<vv"),
            new Puzzle(1, "<<<^<v>>>v<<^<vvvv>v<<^<<v>>>>>>^>"),
            new Puzzle(2, "<^^^^^<<v>^>vvvv>v<^^^>>^<^<vvvv>v<<<<^<<v>>>>>>>^>"),
            new Puzzle(3, "<^^<^>vvvvv<v>^^>>>v>^<^^<<<<^<v>v<<"),
            new Puzzle(4, ">^^<<<>vvv<^^>^<<<<<"),
            new InterPuzzleMovement(">>vv"),
            new Puzzle(6, "v>>>^<<^<<<<^>>vvv>^^v>^^<vvv>>v"),
            new Puzzle(7, "v<<<<v<^>^^^>v>v<<<<<<v<^^v<^>>^>v<v>>>>>>vv>>>"),
            new InterPuzzleMovement(">vvv<"),
            new Puzzle(11, ">>>>>>^^>>>>vvv^^^<<vvvv>>>^^<^^>vvv^^>>>v<<<<<<<<<<<<<^^<"),
            new InterPuzzleMovement("vv<"),
            new Puzzle(12, "vv>>><<vv>vv^^^^vvv<<<<^<<<>vvvv<<<^^^"),
            new Puzzle(13, "vvvv^^^<^>>^^^>>>>>>vv<<<<"),
            new Puzzle(14, "<vv>>^>vv^<<<<<<<<>>>>^^"),
            new Puzzle(15, "^<<vvv^>>>v>>><^<<<<<vvv^^^>>>>>v>>"),
            new Puzzle(16, "<^^^<^>>><<<<^^>>>^^v>v<<<^<vvv<v>><^^^^<<^^>>>^^>v<<<<^<"),
            new InterPuzzleMovement("vv>>>v") { leadingDelay = 5500 }),
        new("Empty",
            new InterPuzzleMovement(">>>vv"),
            new Puzzle(1, "^^>v>><<vv^^<<>v>^<<"),
            new Puzzle(2, "v<<<^^>>>>^<<<<v<^^^v<^>>>^>vv"),
            new Puzzle(3, "<<<v<<^^^vvvvv^^^^>>>>"),
            new Puzzle(4, "<<v>^>vv>>^<^<vvv<vv>^^v"),
            new InterPuzzleMovement("<vvvv"),
            new Puzzle(8, "<^^>><<<<>vvvv^<>><^^^^"),
            new Puzzle(9, "<v<<v>v>^^^v<<^>vvv>>>^<v<^^^^<^><^>^>vvvv^^^>v<^<<vv>^^vvvvvv"),
            new InterPuzzleMovement(">vvv<"),
            new Puzzle(12, "^^^^><^^^vvv>v<^<<<<^^>v>^^^^>^<<^<vv>v"),
            new InterPuzzleMovement("vv<v") { leadingDelay = 4100 }),
        new("Eat",
            new InterPuzzleMovement("vv<<<<v"),
            new Puzzle(1, ">>>v<<v<^^>>>^<<<"),
            new Puzzle(2, ">>^<>^^<vvv<^^^v<^>>^<<>vvvv<^^^>^<>>>"),
            new Puzzle(3, "<v<vv><^^>>^>>v<^<v>>vvv<^^>^<^<vv>vv<^^>^<^<vvv^^^<"),
            new Puzzle(4, "v>>^>v<<<v>>^>vvv>>vvv><^^^^^^^"),
            new InterPuzzleMovement(">>>v"),
            new Puzzle(5, "<vv>>v>^^^<^>>><vvvvvv<v^<<<"),
            new Puzzle(6, "<vv>>^^^>vvv<v><vv>>^^^<^>><vvvv<v^<<<"),
            new InterPuzzleMovement(">vvv<v"),
            new Puzzle(7, ">>>>vv<^<<<v^<<<v>>^>v^>>>>v<<<^<v^<<<v>>^>v^>>v<^<vvvvvv<vv>>"),
            new InterPuzzleMovement("<<<v"),
            new Puzzle(9, ">vvv>^^>vv>^>^<<<<>>^<<^<v<v>^>vv>v<v<^v<^>>v>^^^>>^"),
            new Puzzle(10, ">>>^<<>>vv<<v<^^^^vv<^>>^>vvv<v><<<"),
            new InterPuzzleMovement("vvv") { leadingDelay = 4600 }),
        new("Reference",
            new InterPuzzleMovement("vv<<<v"),
            new Puzzle(1, "<^<<^>^>vvv^<<v>^>vvv^^>>^>><^^^>>^^^"),
            new Puzzle(2, "<<<<^>>v>^^vv>v<<<^<v>>>>v<<<^<vv^>>>^^^^^<v>>>v>"),
            new Puzzle(3, "<vvv>^^<^>>>v>^^v<<<<^^^>^^vvv<^>vvvv<<<<<<vv"),
            new InterPuzzleMovement(">vvv<"),
            new Puzzle(8, "v<<<<v<<<<<v<<<<<^<<<<v^>>>>v>>>^>>>>v<^>>^>>>>v<^>>^>>>>v<^>>^>>>>v<^>>>^"),
            new Puzzle(9, ">>^^vv<<vvv<v<<^>vvv<v>>^^>>vvvv>^^^^^<^>>v>^^^^^^vvvvvv<<vv<<<v<>^>>>^^^^<<"),
            new InterPuzzleMovement("vvv") { leadingDelay = 4600 }),
        new("Swap",
            new InterPuzzleMovement("vv<v"),
            new Puzzle(1, ">vvv>v<^<<<^>^>vvvv>v<<>^^^<v>>v>^^<^>>>>^>vv>v<<>>>^"),
            new InterPuzzleMovement("sva"), // return to hub early using menu, the second normal puzzle is not required and the first one can be solved with fewer actions
            new InterPuzzleMovement(">vvvv<v") { leadingDelay = 4100 })
        // new Puzzle(2, "vvv>>^^>^<<<vv<<<v>>^>vv^^^<v<^>>^<<<<v<^>>>>^<vvv<v>>^>vvv<v>v>^^^<v<<^^>v<v>>>>><<<<<vv"),
        // new InterPuzzleMovement("vvv") { leadingDelay = 4100 })
    }.AsReadOnly();

}